apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: metric
  name: metric
spec:
  ports:
  - name: http-traffic
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: metric
status:
  loadBalancer: {}
