apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: metric
spec:
  selector:
    matchLabels:
      app: metric
  endpoints:
  - port: http-traffic
    path: "/actuator/prometheus"